### PR TITLE
WIP: create a routing path object that manages routes

### LINKED ISSUE #175: Allow manipulation of routes from within page objects
It may be worthwhile to expose the routes variable in the proceed_to loop so that a page can dynamically set which page it will end up on based on application state.

Proposal would basically be to allow something like
```ruby
some_element.on_fill do
  @world.routes.insert_route(SomePage)
end
```

or 

```ruby
def on_page_load
  @world.routes.insert_route(SomePage) if ledger.get_value(APreviousPage, :visit_some_page_checkbox).eql?('checked')
end
```

This is a natural progression from the proceed_to! solution, which does have several drawbacks
- Recalculation is slow because it's limited by the timeout on page identification.
- It's a bit magical in nature

The reason i'm leaning towards this solution is that it, like most of oz, is declarative, and it continues to encapsulate the knowledge of where pages can route to inside of them.

### PR DESCRIPTION
**Pull request by Castone22**
configure router to use this object
allow the current route path to be accessed from core_world
follow new interface in proceed to

This is functionally compatible with route recalculation as well

resolves #175 

Needs unit tests

### CODE REVIEW

**Comment by Castone22** [comment]
This change also relies on some logic introduced in route recalculation, so i'm rebasing it to that branch.

As such, closes #168

**Comment by PanoramicPanda** [comment]
Haven't had a change to pull it down and look yet, but how does this affect the creation of the `page_graph.dot`?

**Comment by Castone22** [comment]
No impact.

The routes that you can insert must have been defined on the page that they're being inserted against. (using add_route)

At some point i also intend to add the ability to dynamically define a route that you're inserting, something like
```ruby
@world.current_route.insert_page(SomePage, using_route: [[:visit, :arg1, :arg2], :param])
```

**Comment by PanoramicPanda** [comment]
So, a route would still be declared via `add_route`... what's the `insert_route` actually doing then?

**Comment by Castone22** [comment]
It sets the next page the router will navigate to in your flow

**Comment by PanoramicPanda** [comment]
Okay, so it forces what the next page actually is, yes? Just making sure I'm getting this right.

**Comment by Castone22** [comment]
Yes, great when you have pages that conditionally show up based on selections.

**Comment by Castone22** [comment]
At some point we're going to get to the point where you feed oz a bunch of different data and tell it to get to each page at the end of a flow lol. Perhaps just have like 90 randomly teenaged datasets per execution and have it basically do an exploratory test 90 times

**Pull request merged**
